;;; ans-vga.el --- CP437 VGA bitmap fonts for ans-mode -*- lexical-binding: t -*-

;; Copyright (C) 2026 William Theesfeld <william@theesfeld.net>
;; Copyright (C) the kbd project contributors for the glyph bitmaps

;; Author: William Theesfeld <william@theesfeld.net>
;; Keywords: multimedia

;; This file is not part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;;; Commentary:

;; Bitmap glyphs for the ANSI raster view.
;;
;; The 8x16 glyphs are the kbd project's default8x16 console font, in
;; CP437 order.  The 8x8 glyphs are the first 256 characters of kbd's
;; drdos8x8 font, also in CP437 order.  Both come from kbd 2.10.0
;; (GPL-2.0-or-later) and are included here under that license's
;; "or later" term.
;;
;; Each glyph is HEIGHT bytes.  Bit 7 of a byte is the leftmost pixel.

;;; Code:

(require 'cl-lib)

(cl-defstruct (ans-vga (:constructor ans-vga--make) (:copier nil))
  "An 8-pixel-wide CP437 bitmap font."
  height
  glyphs)

(defconst ans-vga--8x16-b64
  "AAAAAAAAAAAAAAAAAAAAAAAAfoGlgYG9mYGBfgAAAAAAAH7/2///w+f//34AAAAAAAAAAGz+/v7+
fDgQAAAAAAAAAAAQOHz+fDgQAAAAAAAAAAAYPDzn5+cYGDwAAAAAAAAAGDx+//9+GBg8AAAAAAAA
AAAAABg8PBgAAAAAAAD////////nw8Pn////////AAAAAAA8ZkJCZjwAAAAAAP//////w5m9vZnD
//////8AAB4OGjJ4zMzMzHgAAAAAAAA8ZmZmZjwYfhgYAAAAAAAAPzM/MDAwMHDw4AAAAAAAAH9j
f2NjY2Nn5+bAAAAAAAAAGBjbPOc82xgYAAAAAACAwODw+P748ODAgAAAAAAAAgYOHj7+Ph4OBgIA
AAAAAAAYPH4YGBh+PBgAAAAAAAAAZmZmZmZmZgBmZgAAAAAAAH/b29t7GxsbGxsAAAAAAHzGYDhs
xsZsOAzGfAAAAAAAAAAAAAAA/v7+/gAAAAAAABg8fhgYGH48GH4AAAAAAAAYPH4YGBgYGBgYAAAA
AAAAGBgYGBgYGH48GAAAAAAAAAAAABgM/gwYAAAAAAAAAAAAAAAwYP5gMAAAAAAAAAAAAAAAAMDA
wP4AAAAAAAAAAAAAACRm/2YkAAAAAAAAAAAAABA4OHx8/v4AAAAAAAAAAAD+/nx8ODgQAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAYPDw8GBgYABgYAAAAAABmZmYkAAAAAAAAAAAAAAAAAABsbP5sbGz+
bGwAAAAAGBh8xsLAfAYGhsZ8GBgAAAAAAADCxgwYMGDGhgAAAAAAADhsbDh23MzMzHYAAAAAADAw
MGAAAAAAAAAAAAAAAAAADBgwMDAwMDAYDAAAAAAAADAYDAwMDAwMGDAAAAAAAAAAAABmPP88ZgAA
AAAAAAAAAAAAGBh+GBgAAAAAAAAAAAAAAAAAAAAYGBgwAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAA
AAAAAAAYGAAAAAAAAAAAAgYMGDBgwIAAAAAAAAB8xsbO3vbmxsZ8AAAAAAAAGDh4GBgYGBgYfgAA
AAAAAHzGBgwYMGDAxv4AAAAAAAB8xgYGPAYGBsZ8AAAAAAAADBw8bMz+DAwMHgAAAAAAAP7AwMD8
BgYGxnwAAAAAAAA4YMDA/MbGxsZ8AAAAAAAA/sYGBgwYMDAwMAAAAAAAAHzGxsZ8xsbGxnwAAAAA
AAB8xsbGfgYGBgx4AAAAAAAAAAAYGAAAABgYAAAAAAAAAAAAGBgAAAAYGDAAAAAAAAAABgwYMGAw
GAwGAAAAAAAAAAAAfgAAfgAAAAAAAAAAAABgMBgMBgwYMGAAAAAAAAB8xsYMGBgYABgYAAAAAAAA
fMbGxt7e3tzAfAAAAAAAABA4bMbG/sbGxsYAAAAAAAD8ZmZmfGZmZmb8AAAAAAAAPGbCwMDAwMJm
PAAAAAAAAPhsZmZmZmZmbPgAAAAAAAD+ZmJoeGhgYmb+AAAAAAAA/mZiaHhoYGBg8AAAAAAAADxm
wsDA3sbGZjoAAAAAAADGxsbG/sbGxsbGAAAAAAAAPBgYGBgYGBgYPAAAAAAAAB4MDAwMDMzMzHgA
AAAAAADmZmZseHhsZmbmAAAAAAAA8GBgYGBgYGJm/gAAAAAAAMPn///bw8PDw8MAAAAAAADG5vb+
3s7GxsbGAAAAAAAAfMbGxsbGxsbGfAAAAAAAAPxmZmZ8YGBgYPAAAAAAAAB8xsbGxsbG1t58DA4A
AAAA/GZmZnxsZmZm5gAAAAAAAHzGxmA4DAbGxnwAAAAAAAD/25kYGBgYGBg8AAAAAAAAxsbGxsbG
xsbGfAAAAAAAAMPDw8PDw8NmPBgAAAAAAADDw8PDw9vb/2ZmAAAAAAAAw8NmPBgYPGbDwwAAAAAA
AMPDw2Y8GBgYGDwAAAAAAAD/w4YMGDBgwcP/AAAAAAAAPDAwMDAwMDAwPAAAAAAAAACAwOBwOBwO
BgIAAAAAAAA8DAwMDAwMDAw8AAAAABA4bMYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAMDAY
AAAAAAAAAAAAAAAAAAAAAAAAeAx8zMzMdgAAAAAAAOBgYHhsZmZmZnwAAAAAAAAAAAB8xsDAwMZ8
AAAAAAAAHAwMPGzMzMzMdgAAAAAAAAAAAHzG/sDAxnwAAAAAAAA4bGRg8GBgYGDwAAAAAAAAAAAA
dszMzMzMfAzMeAAAAOBgYGx2ZmZmZuYAAAAAAAAYGAA4GBgYGBg8AAAAAAAABgYADgYGBgYGBmZm
PAAAAOBgYGZseHhsZuYAAAAAAAA4GBgYGBgYGBg8AAAAAAAAAAAA5v/b29vb2wAAAAAAAAAAANxm
ZmZmZmYAAAAAAAAAAAB8xsbGxsZ8AAAAAAAAAAAA3GZmZmZmfGBg8AAAAAAAAHbMzMzMzHwMDB4A
AAAAAADcdmZgYGDwAAAAAAAAAAAAfMZgOAzGfAAAAAAAABAwMPwwMDAwNhwAAAAAAAAAAADMzMzM
zMx2AAAAAAAAAAAAw8PDw2Y8GAAAAAAAAAAAAMPDw9vb/2YAAAAAAAAAAADDZjwYPGbDAAAAAAAA
AAAAxsbGxsbGfgYM+AAAAAAAAP7MGDBgxv4AAAAAAAAOGBgYcBgYGBgOAAAAAAAAGBgYGAAYGBgY
GAAAAAAAAHAYGBgOGBgYGHAAAAAAAAB23AAAAAAAAAAAAAAAAAAAAAAQOGzGxsb+AAAAAAAAADxm
wsDAwMJmPAwGfAAAAADMAADMzMzMzMx2AAAAAAAMGDAAfMb+wMDGfAAAAAAAEDhsAHgMfMzMzHYA
AAAAAADMAAB4DHzMzMx2AAAAAABgMBgAeAx8zMzMdgAAAAAAOGw4AHgMfMzMzHYAAAAAAAAAADxm
YGBmPAwGPAAAAAAQOGwAfMb+wMDGfAAAAAAAAMYAAHzG/sDAxnwAAAAAAGAwGAB8xv7AwMZ8AAAA
AAAAZgAAOBgYGBgYPAAAAAAAGDxmADgYGBgYGDwAAAAAAGAwGAA4GBgYGBg8AAAAAADGABA4bMbG
/sbGxgAAAAA4bDgAOGzGxv7GxsYAAAAAGDBgAP5mYHxgYGb+AAAAAAAAAAAAbjsbftjcdwAAAAAA
AD5szMz+zMzMzM4AAAAAABA4bAB8xsbGxsZ8AAAAAAAAxgAAfMbGxsbGfAAAAAAAYDAYAHzGxsbG
xnwAAAAAADB4zADMzMzMzMx2AAAAAABgMBgAzMzMzMzMdgAAAAAAAMYAAMbGxsbGxn4GDHgAAMYA
fMbGxsbGxsZ8AAAAAADGAMbGxsbGxsbGfAAAAAAAGBh+w8DAwMN+GBgAAAAAADhsZGDwYGBgYOb8
AAAAAAAAw2Y8GP8Y/xgYGAAAAAAA/GZmfGJmb2ZmZvMAAAAAAA4bGBgYfhgYGBgY2HAAAAAYMGAA
eAx8zMzMdgAAAAAADBgwADgYGBgYGDwAAAAAABgwYAB8xsbGxsZ8AAAAAAAYMGAAzMzMzMzMdgAA
AAAAAHbcANxmZmZmZmYAAAAAdtwAxub2/t7OxsbGAAAAAAA8bGw+AH4AAAAAAAAAAAAAOGxsOAB8
AAAAAAAAAAAAAAAwMAAwMGDAxsZ8AAAAAAAAAAAAAP7AwMDAAAAAAAAAAAAAAAD+BgYGBgAAAAAA
AMDAwsbMGDBgzpsGDB8AAADAwMLGzBgwZs6WPgYGAAAAABgYABgYGDw8PBgAAAAAAAAAAAA2bNhs
NgAAAAAAAAAAAAAA2Gw2bNgAAAAAAAARRBFEEUQRRBFEEUQRRBFEVapVqlWqVapVqlWqVapVqt13
3Xfdd9133Xfdd9133XcYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGPgYGBgYGBgYGBgYGBgY+Bj4GBgY
GBgYGBg2NjY2NjY29jY2NjY2NjY2AAAAAAAAAP42NjY2NjY2NgAAAAAA+Bj4GBgYGBgYGBg2NjY2
NvYG9jY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NgAAAAAA/gb2NjY2NjY2NjY2NjY2NvYG/gAAAAAA
AAAANjY2NjY2Nv4AAAAAAAAAABgYGBgY+Bj4AAAAAAAAAAAAAAAAAAAA+BgYGBgYGBgYGBgYGBgY
GB8AAAAAAAAAABgYGBgYGBj/AAAAAAAAAAAAAAAAAAAA/xgYGBgYGBgYGBgYGBgYGB8YGBgYGBgY
GAAAAAAAAAD/AAAAAAAAAAAYGBgYGBgY/xgYGBgYGBgYGBgYGBgfGB8YGBgYGBgYGDY2NjY2NjY3
NjY2NjY2NjY2NjY2NjcwPwAAAAAAAAAAAAAAAAA/MDc2NjY2NjY2NjY2NjY29wD/AAAAAAAAAAAA
AAAAAP8A9zY2NjY2NjY2NjY2NjY3MDc2NjY2NjY2NgAAAAAA/wD/AAAAAAAAAAA2NjY2NvcA9zY2
NjY2NjY2GBgYGBj/AP8AAAAAAAAAADY2NjY2Njb/AAAAAAAAAAAAAAAAAP8A/xgYGBgYGBgYAAAA
AAAAAP82NjY2NjY2NjY2NjY2NjY/AAAAAAAAAAAYGBgYGB8YHwAAAAAAAAAAAAAAAAAfGB8YGBgY
GBgYGAAAAAAAAAA/NjY2NjY2NjY2NjY2NjY2/zY2NjY2NjY2GBgYGBj/GP8YGBgYGBgYGBgYGBgY
GBj4AAAAAAAAAAAAAAAAAAAAHxgYGBgYGBgY/////////////////////wAAAAAAAAD/////////
///w8PDw8PDw8PDw8PDw8PDwDw8PDw8PDw8PDw8PDw8PD/////////8AAAAAAAAAAAAAAAAAAHbc
2NjY3HYAAAAAAAB4zMzM2MzGxsbMAAAAAAAA/sbGwMDAwMDAwAAAAAAAAAAA/mxsbGxsbGwAAAAA
AAAA/sZgMBgwYMb+AAAAAAAAAAAAftjY2NjYcAAAAAAAAAAAZmZmZmZ8YGDAAAAAAAAAAHbcGBgY
GBgYAAAAAAAAAH4YPGZmZjwYfgAAAAAAAAA4bMbG/sbGbDgAAAAAAAA4bMbGxmxsbGzuAAAAAAAA
HjAYDD5mZmZmPAAAAAAAAAAAAH7b29t+AAAAAAAAAAAAAwZ+29vzfmDAAAAAAAAAHDBgYHxgYGAw
HAAAAAAAAAB8xsbGxsbGxsYAAAAAAAAAAP4AAP4AAP4AAAAAAAAAAAAYGH4YGAAA/wAAAAAAAAAw
GAwGDBgwAH4AAAAAAAAADBgwYDAYDAB+AAAAAAAADhsbGxgYGBgYGBgYGBgYGBgYGBgYGNjY2HAA
AAAAAAAAABgYAH4AGBgAAAAAAAAAAAAAdtwAdtwAAAAAAAAAOGxsOAAAAAAAAAAAAAAAAAAAAAAA
ABgYAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAADwwMDAwM7GxsPBwAAAAAANhsbGxsbAAAAAAAAAAA
AABw2DBgyPgAAAAAAAAAAAAAAAAAfHx8fHx8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
  "Base64 of 256 CP437 glyphs, 16 bytes each.")

(defconst ans-vga--8x8-b64
  "AAAAAAAAAAB+gaWBvZmBfn7/2//D5/9+bP7+/nw4EAAQOHz+fDgQABg8POfnGDwAEDh8/nwQOAAA
ABg8GAAAAP//58Pn////AAAYJBgAAAD//+fb5////xwMEHyCgnwAfIKCfBA4EAAAHx4QEPDgAAA+
PiIu7MAAEFQ4bDhUEAAAQHB8cEAAAAAEHHwcBAAAGDx+GBh+PBgoKCgoKAAoAH/b21sbGxsbPEJ4
JCQeQjwAAAAA/v7+ABg8fhh+PBh+GDx+GBgYGAAAGBgYGH48GAAYDP4MGAAAADBg/mAwAAAAAMDA
wP4AAAAkZv9mJAAAABgYPDx+fgAAfn48PBgYAAAAAAAAAAAAGDw8GBgAGABsbGwAAAAAAERE/kT+
REQAMHzAeAz4MAAAxswYMGbGADhsOHbczHYAcDBgAAAAAAAYMGBgYDAYAGAwGBgYMGAAAMx4/njM
AAAAMDD8MDAAAAAAAAAAcDBgAAAA/AAAAAAAAAAAADAwAAYMGDBgwIAAfMbO1ubGfAAwcDAwMDD8
AHjMDDhgwPwAeMwMOAzMeAAcNGzM/gwMAPzA+AwMzHgAOGDA+MzMeAD8DAwYMGBgAHjMzHjMzHgA
eMzMfAwYcAAAADAwADAwAAAAMDAAcDBgGDBgwGAwGAAAAPwA/AAAAGAwGAwYMGAAeMwMGDAAMAB8
gp62noB4ADB4zMz8zMwA/GZmfGZm/AA8ZsDAwGY8APhsZmZmbPgA/sLI+MjC/gD+wsj4yMDAADxm
wMDOZj4AxsbG/sbGxgA8GBgYGBg8AA4GBgZmZjwAxszY8NjMxgDwYGBgYGL+AILG7tbWxsYAxub2
3s7GxgA4bMbGxmw4APxmZmZ8YPAAOGzGxtZsPAb4zMz42MzGAHzG4DwGxnwAfloYGBgYGADGxsbG
xsZ8AMbGxsZsOBAAxsbG1tZsbADGxmw4bMbGAGZmZjwYGBgA/owYMGDC/gA8MDAwMDA8AMBgMBgM
BgIAPAwMDAwMPAAQOGzGAAAAAAAAAAAAAAD+ODAYAAAAAAAAAHgMfMx2AOBgfGZmZtwAAAB8xsDG
fAAcDHzMzMx2AAAAPGZ+YDwAHDYwfjAwMAAAAHbMzHwM+GBgfGZmZmYAGAA4GBgYfgAMADwMDAxs
OGBgZmx4bGYAOBgYGBgYfgAAAMz+1tbGAAAA3GZmZmYAAAB8xsbGfAAAANxmZnxg4AAAdszMfAwO
AADcZmBg8AAAAD5gPAZ8AAAwfjAwNhwAAADMzMzMdgAAAGZmZjwYAAAAxtbWbGwAAADGbDhsxgAA
AGZmZjwYcAAAfkwYMn4ADhgYcBgYDgAYGBgYGBgYAHAYGA4YGHAAYpKMAAAAAAAQOGzGxsb+ADxm
wMBmPAw4ZgBmZmZmfgAGCDxmfmA8ABhmADwGdj4AZgA8Bj5mPgAgEDwGPmY+AAgUPAY+Zj4AAAA+
YGA+DDgYZgA8bmA8AGYAPGZ+YDwAIBA8Zn5gPABmADgYGBh+ABhmADgYGH4AIBA4GBgYfgBmGDxm
Zn5mADxmPGZmfmYABgx+YHxgfgAAAOwSfpDuAD5szP7MzM4AGGYAPGZmPABmADxmZmY8AGAQPGZm
ZjwAGGYAZmZmPgBgEGZmZmY+AGYAZmZmPBhwYxw2Y2M2HABmAGZmZmY8ABgYPGBgPBgYHDYwfDAg
fgBmZjx+GH4YGPDY2PzOzM4ADhgYfhgYcAAGCDwGPmY+AAYIOBgYGH4ABgg8ZmZmPAAGCGZmZmY+
AHJOAHxmZmYAMkzmttrOxgB4DHzMfAD8AHjMzMx4APwAADAAMGDAzHgAAAD8wMAAAAAAAPwMDAAA
gICAvIYcMD6AgICOliY+BgAwADAweHgwAAA2bNhsNgAAANhsNmzYACKIIogiiCKIVapVqlWqVaq7
7rvuu+677hgYGBgYGBgYGBgYGPgYGBgYGBj4GPgYGDY2Njb2NjY2AAAAAP42NjYAAAD4GPgYGDY2
NvYG9jY2NjY2NjY2NjYAAAD+BvY2NjY2NvYG/gAANjY2Nv4AAAAYGBj4GPgAAAAAAAD4GBgYGBgY
GB8AAAAYGBgY/wAAAAAAAAD/GBgYGBgYGB8YGBgAAAAA/wAAABgYGBj/GBgYGBgYHxgfGBg2NjY2
NzY2NjY2NjcwPwAAAAAAPzA3NjY2Njb3AP8AAAAAAP8A9zY2NjY2NzA3NjYAAAD/AP8AADY2NvcA
9zY2GBgY/wD/AAA2NjY2/wAAAAAAAP8A/xgYAAAAAP82NjY2NjY2PwAAABgYGB8YHwAAAAAAHxgf
GBgAAAAAPzY2NjY2Njb/NjY2GBgY/xj/GBgYGBgY+AAAAAAAAAAfGBgY//////////8AAAAA////
//Dw8PDw8PDwDw8PDw8PDw//////AAAAAAAAdtzI3HYAeMzYzMz4wMD+xsDAwMDAAAAA/mxsbGYA
/mAwGDBg/gAAAH7IzMx4AAAAzMzM+MCAAAD+MDAwHAA8GH7Dfhg8ADhsxv7GbDgAfMbGxsZs7gAc
MBh8zMx4AAAAZtvbZgAAAwZ+29t+YMA8YMD8wGA8AHjMzMzMzMwAAPwA/AD8AAAwMPwwMAD8AGAw
HDBgAPwAGDDgMBgA/AAOGxsYGBgYGBgYGBgY2NhwMDAA/AAwMAAAcpwAcpwAADhsbDgAAAAAAAAw
MAAAAAAAAAAwAAAAAA4ICIjIaDgYeGxsbGwAAAB4DDhgfAAAAAAAeHh4eAAAAAAAAAAAAAA="
  "Base64 of 256 CP437 glyphs, 8 bytes each.")

(defconst ans-vga--8x16
  (let ((raw (base64-decode-string ans-vga--8x16-b64)))
    (unless (= (length raw) (* 256 16))
      (error "Bad 8x16 VGA font"))
    (ans-vga--make :height 16 :glyphs raw))
  "IBM VGA 8x16 font used for 80x25 ANSI.")

(defconst ans-vga--8x8
  (let ((raw (base64-decode-string ans-vga--8x8-b64)))
    (unless (= (length raw) (* 256 8))
      (error "Bad 8x8 VGA font"))
    (ans-vga--make :height 8 :glyphs raw))
  "8x8 font used when SAUCE names a VGA50 / 80x50 font.")

(defun ans-vga-font (height)
  "Return the built-in VGA font whose glyph height is HEIGHT.
HEIGHT is 8 or 16."
  (cond
   ((= height 8) ans-vga--8x8)
   ((= height 16) ans-vga--8x16)
   (t (error "No VGA font of height %s" height))))

(defun ans-vga-byte (font char row)
  "Return the bitmap byte for CHAR at ROW in FONT.
Bit 7 is the leftmost pixel."
  (aref (ans-vga-glyphs font)
        (+ (* char (ans-vga-height font)) row)))

(provide 'ans-vga)
;;; ans-vga.el ends here

;; Local Variables:
;; package-lint-main-file: "ans-mode.el"
;; End:
